# Automatically generated by Pynguin.
import tests.integrations.all_modules as module0


def test_case_0():
    try:
        var0 = -146.93578
        var1 = 726.461422
        var2 = -171
        var3 = -2400
        var4 = -2478
        var5 = module0.test_all(var0, var1, var2, var2, var3, var3, var3,
            var4, var3)
    except BaseException:
        pass


def test_case_1():
    try:
        var0 = -3449.0
        var1 = None
        var2 = -111
        var3 = 2909
        var4 = 3318
        var5 = -2048
        var6 = module0.test_all(var0, var0, var1, var1, var2, var3, var2,
            var4, var5)
        var7 = -122.0
        var8 = None
        var9 = 179.071
        var10 = 88
        var11 = -4133.02
        var12 = -2105.0
        var13 = 7000
        var14 = None
        var15 = 1927
        var16 = -1208
        var17 = module0.test_all(var11, var12, var4, var13, var13, var2,
            var14, var15, var16)
        var18 = module0.test_all(var8, var9, var5, var1, var4, var4, var2,
            var10, var1)
        var19 = -3794.633
        var20 = -366
        var21 = 3773
        var22 = module0.test_all(var19, var0, var20, var4, var4, var4,
            var21, var21, var21)
        var23 = -4234.584
        var24 = 322
        var25 = 544
        var26 = -1335
        var27 = 3880
        var28 = 876
        var29 = module0.test_all(var0, var23, var1, var24, var25, var26,
            var5, var27, var28)
        var30 = -2252
        var31 = None
        var32 = -1108
        var33 = -102
        var34 = module0.test_all(var7, var7, var30, var31, var32, var33,
            var32, var31, var32)
    except BaseException:
        pass


def test_case_2():
    try:
        var0 = -2324.161
        var1 = -1769
        var2 = 752
        var3 = 540
        var4 = 2010
        var5 = module0.test_all(var0, var0, var1, var1, var2, var3, var2,
            var4, var2)
    except BaseException:
        pass


def test_case_3():
    try:
        var0 = -1766.582
        var1 = 2130.285768
        var2 = 563
        var3 = -2775
        var4 = 1278.634133
        var5 = -4393.623
        var6 = -1220
        var7 = -60
        var8 = None
        var9 = -154
        var10 = module0.test_all(var4, var5, var2, var6, var7, var2, var8,
            var9, var2)
        var11 = None
        var12 = module0.test_all(var0, var1, var2, var3, var2, var3, var2,
            var11, var2)
        var13 = -342.0
        var14 = 1377
        var15 = -1594
        var16 = 1418
        var17 = 501
        var18 = module0.test_all(var13, var13, var14, var14, var15, var16,
            var17, var15, var15)
        var19 = -1812.6
        var20 = -3344.176428
        var21 = 227
        var22 = 1433
        var23 = -2960
        var24 = 357
        var25 = 2485
        var26 = -1784
        var27 = module0.test_all(var19, var1, var23, var24, var8, var25,
            var26, var7, var6)
        var28 = 2388
        var29 = -245
        var30 = module0.test_all(var19, var20, var21, var22, var28, var21,
            var28, var29, var28)
    except BaseException:
        pass


def test_case_4():
    try:
        var0 = -2416.1578
        var1 = 1517.46556
        var2 = 2377
        var3 = None
        var4 = 1416.158816
        var5 = -2095
        var6 = 2150
        var7 = -1772
        var8 = module0.test_all(var1, var4, var5, var6, var2, var3, var7,
            var5, var6)
        var9 = module0.test_all(var0, var0, var2, var2, var2, var2, var3,
            var3, var2)
        var10 = 1809
        var11 = 3926.4594
        var12 = 894
        var13 = 1235
        var14 = 2733
        var15 = module0.test_all(var1, var11, var10, var3, var12, var13,
            var14, var2, var14)
        var16 = -284
        var17 = -1391
        var18 = -2883.0
        var19 = -885.0
        var20 = 1721
        var21 = 2497
        var22 = -805
        var23 = -3993
        var24 = module0.test_all(var18, var19, var16, var2, var20, var21,
            var17, var22, var23)
        var25 = 556
        var26 = -1936
        var27 = module0.test_all(var0, var1, var10, var16, var17, var10,
            var25, var25, var26)
    except BaseException:
        pass


def test_case_5():
    try:
        var0 = 651.0
        var1 = 165
        var2 = 2811
        var3 = -410
        var4 = -2494
        var5 = module0.test_all(var0, var0, var1, var2, var2, var3, var4,
            var4, var4)
        var6 = 186
        var7 = -2340
        var8 = -1868
        var9 = -5426
        var10 = -914.55475
        var11 = 994
        var12 = -1612
        var13 = -293
        var14 = None
        var15 = 732.0
        var16 = 2190
        var17 = 1085
        var18 = module0.test_all(var15, var10, var16, var4, var14, var3,
            var2, var13, var17)
        var19 = module0.test_all(var0, var10, var11, var12, var13, var1,
            var3, var14, var8)
        var20 = -2923
        var21 = module0.test_all(var0, var0, var7, var1, var8, var1, var7,
            var9, var20)
        var22 = 2951
        var23 = 3741
        var24 = 324
        var25 = module0.test_all(var0, var0, var6, var22, var22, var22,
            var2, var23, var24)
    except BaseException:
        pass


def test_case_6():
    try:
        var0 = None
        var1 = -3026.21374
        var2 = 2379.964
        var3 = -2163.289407
        var4 = -1778
        var5 = -1204
        var6 = -3520
        var7 = -359.532631
        var8 = 578
        var9 = module0.test_all(var0, var7, var5, var4, var8, var4, var4,
            var8, var4)
        var10 = -1654
        var11 = -4526
        var12 = 1707
        var13 = module0.test_all(var2, var3, var4, var5, var6, var10, var11,
            var12, var10)
        var14 = -879.896961
        var15 = -3517
        var16 = -1724.0
        var17 = 2729
        var18 = -754
        var19 = -933
        var20 = module0.test_all(var16, var1, var10, var6, var17, var12,
            var18, var19, var6)
        var21 = 820
        var22 = -1158
        var23 = module0.test_all(var1, var14, var15, var15, var15, var15,
            var15, var21, var22)
        var24 = 2421
        var25 = -2265
        var26 = 825
        var27 = -4008
        var28 = module0.test_all(var0, var1, var24, var24, var25, var24,
            var26, var25, var27)
    except BaseException:
        pass


def test_case_7():
    try:
        var0 = 1437.68
        var1 = None
        var2 = -2191
        var3 = -65
        var4 = 602
        var5 = -821
        var6 = 1237
        var7 = module0.test_all(var0, var1, var3, var2, var2, var5, var6,
            var5, var3)
        var8 = module0.test_all(var0, var1, var2, var2, var3, var3, var4,
            var3, var2)
        var9 = 2912.2
        var10 = None
        var11 = -2811.24553
        var12 = None
        var13 = -1211.2754
        var14 = -1231
        var15 = 1725
        var16 = module0.test_all(var12, var13, var3, var14, var3, var4,
            var15, var2, var2)
        var17 = -970
        var18 = -684
        var19 = -717
        var20 = module0.test_all(var11, var1, var17, var18, var19, var2,
            var6, var6, var4)
        var21 = -3491
        var22 = 25
        var23 = 580
        var24 = -2098
        var25 = -2890
        var26 = 983
        var27 = 1117
        var28 = None
        var29 = 2413
        var30 = None
        var31 = -2332
        var32 = -560
        var33 = module0.test_all(var28, var11, var27, var23, var29, var2,
            var30, var31, var32)
        var34 = -4227
        var35 = module0.test_all(var1, var9, var25, var21, var24, var26,
            var27, var4, var34)
        var36 = -438
        var37 = module0.test_all(var9, var9, var10, var21, var22, var23,
            var24, var36, var21)
    except BaseException:
        pass
